### ISSUE TITLE
There is a problem when deploying:

### ISSUE THREAD

**Issue by wwyf** [wwyf/Waterfall-backend#21]
There is a problem when deploying:
```
$ openssl aes-256-cbc -K $encrypted_70ca040df3bb_key -iv $encrypted_70ca040df3bb_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
before_deploy.2
0.01s$ eval "$(ssh-agent -s)"
Agent pid 3930
before_deploy.3
0.00s$ chmod 600 /tmp/deploy_rsa
before_deploy.4
0.02s$ ssh-add /tmp/deploy_rsa
Identity added: /tmp/deploy_rsa (/tmp/deploy_rsa)
dpl_0
1.64s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.10.8
Parsing documentation for dpl-1.10.8
Installing ri documentation for dpl-1.10.8
Done installing documentation for dpl after 0 seconds
1 gem installed
dpl.1
Installing deploy dependencies
Successfully installed dpl-script-1.10.8
Parsing documentation for dpl-script-1.10.8
Installing ri documentation for dpl-script-1.10.8
Done installing documentation for dpl-script after 0 seconds
1 gem installed
/home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:54:in `system': no implicit conversion of nil into String (TypeError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:54:in `shell'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-script-1.10.8/lib/dpl/provider/script.rb:19:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.8/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
dpl.2
Preparing deploy
dpl.3
Deploying application
failed to deploy
```

**Comment by wwyf** [comment]
#22 
try to fix.

**Comment by wwyf** [comment]
avoid use deploy.
I can use "after_success"

**Comment by wwyf** [comment]
run the script like this
```
#!/bin/bash
set -x
echo $TRAVIS_BRANCH
if [ "$TRAVIS_BRANCH" == "master" ]; then
    openssl aes-256-cbc -K $encrypted_70ca040df3bb_key -iv $encrypted_70ca040df3bb_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    eval "$(ssh-agent -s)"
    chmod 600 /tmp/deploy_rsa
    ssh-add /tmp/deploy_rsa
    ssh wyf@waterfall.wwyf.top "cd Waterfall/Waterfall-backend && git pull"
fi
```
so it can auto deploy when I update the master  branch

**Comment by wwyf** [comment]
#23 fix it.
